version: "3.8"

services:
  # svelte
  sc_svelteapp:
    container_name: ct_svelteapp
    build:
     context: ./app
     dockerfile: Dockerfile.prod
    restart: always
    expose:
      - 3000
    volumes:
      - ./app/nginx_prod.conf:/etc/nginx/nginx.conf
    networks:
      - internal

  # nginx
  sc_nginx:
    image: nginx:stable-alpine3.17-slim
    container_name: ct_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/prod/nginx.conf:/etc/nginx/nginx.conf
      - ./CERTBOT/certbot/conf:/etc/letsencrypt
      - ./CERTBOT/certbot/www:/var/www/certbot
    depends_on:
      - sc_svelteapp
    restart: always
    networks:
     - internal
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    container_name: certbot
    image: certbot/certbot
    networks:
        internal:
          aliases:
            - "certbot"
    restart: unless-stopped
    entrypoint:  "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./CERTBOT/certbot/conf:/etc/letsencrypt
      - ./CERTBOT/certbot/www:/var/www/certbot

  #mongo api
  sc_nodemongoapi:
    container_name: ct_nodemongoapi
    build:
     context: ./mongo
     dockerfile: Dockerfile.prod
    restart: always
    expose:
      - 3001
    networks:
     - internal

  # go back
  sc_goapp:
   container_name: ct_goapp
   build:
    context: ./back
    dockerfile: Dockerfile.prod
   restart: always
   expose:
     - 8080
   networks:
     - internal

  #mongodb
  sc_mongodb:
   image: mongo:4.0.28-xenial
   container_name: sc_mongodb
   restart: always
   expose:
     - 27017
   environment:
     MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
   env_file: .env
   volumes:
     - ./mongodata:/data/db
   networks:
    - internal


networks:
  internal: 
    driver: bridge
