version: "3.8"

services:
  # svelte
  sc_svelteapp:
    container_name: ct_svelteapp
    build:
     context: ./app
     dockerfile: Dockerfile.dev
    restart: always
    expose:
      - 3000
    volumes:
      - ./app:/app
    networks:
      - internal

  #mongo api
  sc_nodemongoapi:
    container_name: ct_nodemongoapi
    build:
     context: ./mongo
     dockerfile: Dockerfile.dev
    restart: always
    expose: 
      - 3001 
    volumes:
      - ./mongo:/app
    networks:
     - internal

  # nginx
  sc_nginx:
    image: nginx:stable-alpine3.17-slim
    container_name: ct_nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/dev/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - sc_svelteapp
    restart: always
    networks:
     - internal

  # go back
  sc_goapp:
   container_name: ct_goapp
   build:
    context: ./back/
    dockerfile: Dockerfile.dev
   restart: always
   volumes:
     - ./back/app:/app
   expose:
     - 8080
   ports:
     - 3002:8080
   networks:
     - internal

  #mongodb
  sc_mongodb:
   image: mongo:4.0.28-xenial
   container_name: sc_mongodb
   restart: always
   expose:
     - 27017
   environment:
     MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
   env_file: .env
   volumes:
     - ./mongodata:/data/db
   networks:
    - internal


networks:
  internal: 
    driver: bridge
