version: "3.8"

services:
  # svelte
  sc_svelteapp:
    container_name: ct_svelteapp
    build:
     context: ./app
     dockerfile: Dockerfile.prod
    restart: always
    expose:
      - 3000
    volumes:
      - ./svelteapp/nginx_prod.conf:/etc/nginx/nginx.conf
    networks:
      - internal

  # nginx
  sc_nginx:
    image: nginx:stable-alpine3.17-slim
    container_name: ct_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/prod/nginx.conf:/etc/nginx/nginx.conf
      - ./CERTBOT/certbot/conf:/etc/letsencrypt
      - ./CERTBOT/certbot/www:/var/www/certbot
    depends_on:
      - sc_svelteapp
    restart: always
    networks:
     - internal
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    container_name: certbot
    image: certbot/certbot
    networks:
        internal:
          aliases:
            - "certbot"
    restart: unless-stopped
    entrypoint:  "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./CERTBOT/certbot/conf:/etc/letsencrypt
      - ./CERTBOT/certbot/www:/var/www/certbot

  # go back
  sc_goapp:
   container_name: ct_goapp
   build:
    context: ./goapp
    dockerfile: Dockerfile.prod
   restart: always
   env_file: 
     - ./goapp/goapp.env
   expose:
     - 8080
   networks:
     - internal

  #mongodb
  sc_mongodb:
   image: mongo:4.0.28-xenial
   container_name: ct_mongodb
   restart: always
   expose:
     - 27017
   env_file: 
     - ./mongodb/mongodb.env
   volumes:
     - ./mongodb/data:/data/db
   networks:
    - internal


networks:
  internal: 
    driver: bridge
