FROM node:19-alpine3.16

ENV NODE_ENV development

RUN npm install

WORKDIR /app

COPY package*.json pnpm-lock.yaml ./

RUN npm i

COPY . .

ENV NODE_ENV production

RUN npm run build

FROM node:19-alpine3.16

WORKDIR /app

COPY --from=0 /app .

COPY . .

EXPOSE 3000

CMD ["node", "./build"]