FROM node:19-alpine3.16

ENV NODE_ENV development

WORKDIR /app

COPY . .

RUN npm install

ENV NODE_ENV production

RUN npm run build

FROM nginx:stable-alpine3.17-slim

WORKDIR /usr/share/nginx/app

COPY --from=0 /app/build .
