# air.toml

root = "."
tmp_dir = "tmp"
build_args = ["-tags", "development"]

[build]
  binary = "./main"
  watch = true
  exclude_dir = ["nuts", "nuts_tmp"]

[log]
  error_log = "logs/error.log"
  warn_log = "logs/warn.log"
  info_log = "logs/info.log"
  debug_log = "logs/debug.log"
